# encoding: utf-8

#
# Copyright © 2015 ATS Advanced Telematic Systems GmbH
#
# This file is part of Docker Launcher.
#
# Docker Launcher is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# Docker Launcher is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# Docker Launcher. If not, see <http://www.gnu.org/licenses/>.
#



from launcher.util.configuration import LauncherConf
from launcher.util.stack_config import StackConf
from launcher.ansible.executor import generate as playbook_generate
from launcher.ansible.teardown import generate as teardown_generate
from launcher.util.dict_wrapper import SchemaError
import pytest
import yaml

CONFIG = "tests/test-config.yml"


def parse_yaml_config(path):
    """Parse a yaml file"""
    with open(path) as conf_stream:
        conf = yaml.safe_load(conf_stream)
    return conf


def run_playbook_test(stackfile, playbook, index=False, configfile=CONFIG):
    """Test a playbook"""
    run_generator_test(playbook_generate, stackfile,
                       playbook, index, configfile)


def run_teardown_test(stackfile, playbook, index=False, configfile=CONFIG):
    """Test a teardown playbook"""
    run_generator_test(teardown_generate, stackfile,
                       playbook, index, configfile)


def run_generator_test(generator, stackfile, playbook,
                       index=False, configfile=CONFIG):
    """
    Run a test by comparing an expected playbook with one generated by the
    generator function
    """
    with open(configfile) as launcher_conf:
        config = LauncherConf(launcher_conf)
    with open(stackfile) as stack_conf:
        stack = StackConf(stack_conf)
        generated_playbook = yaml.load(generator(stack, config))
    expected_playbook = parse_yaml_config(playbook)
    if not index:
        assert generated_playbook == expected_playbook
    else:
        for i in index:
            assert generated_playbook[i] == expected_playbook[i]


def run_schema_error_test(stack):
    """
    Generate a playbook from a stack conf, that is expected to raise an
    Exception
    """
    with pytest.raises(SchemaError):
        with open(CONFIG, 'r') as configuration:
            config = LauncherConf(configuration)
            yaml.load(playbook_generate(StackConf(stack), config))

